spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soptseminar
    username: jayson
    password: dpvmzlffk1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace