spring:
  config:
    activate:
      on-profile: set2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://week7seminar.cjagzuyseoub.ap-northeast-2.rds.amazonaws.com:5432/week7seminar
    username: week7seminar
    password: Week7seminar!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8082