spring:
  profiles:
    active: set1
---
spring:
  config:
    activate:
      on-profile: set1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://week7seminar.cjagzuyseoub.ap-northeast-2.rds.amazonaws.com:5432/week7seminar
    username: <-RDS 사용자 이름->
    password: <-RDS 사용자 비밀번호->
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8081

